esphome:
  name: ws2805-light
  friendly_name: WS2805 Light
      
esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://Jak3zz/esphome-ws2805
    components: [rgbwc_neopixelbus]

light:
  - platform: rgbwc_neopixelbus
    name: Ambiance Light
    pin: 16
    num_leds: 10
    default_transition_length: 500ms
    restore_mode: RESTORE_AND_OFF